Proyecto/AppCoder/urls.py
from django.urls import path
from AppCoder.views import about_view,cargar_perfil_view,crear_perfil_view,delete_blog_view,cargar_blog_view,crear_comentario_view,logout_view,login_view, inicio_view,buscar_blog_view,detalle_blog_view,ver_blog_view,nuevo_blog_view,crear_blog_view


urlpatterns = [    
    path("inicio/", inicio_view,name="home"),
    path("login/", login_view, name="login"),
    path("logout/",logout_view, name="logout"),
    path("about/",about_view, name="about"),
    path("Buscarblog/",buscar_blog_view, name="Buscarblog"),
    path("detalleblog/",detalle_blog_view, name="detalleblog"),
    path("verblog/<id_blog>",ver_blog_view, name="verblog"),
    path("nuevoblog/", crear_blog_view,name="nuevoblog"),
    path("comentario/", crear_comentario_view,name="newcomentario"),
    path("updateblog/<id_blog>",cargar_blog_view, name="updateblog"),
    path("deleteblog/<id_blog>",delete_blog_view, name="deleteblog"),
    path("nuevoperfil/", crear_perfil_view,name="nuevoperfil"),
    path("updateperfil/<id_user>",cargar_perfil_view, name="updateperfil"),
    
    
  
]

Proyecto/Proyecto/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("AppCoder/", include("AppCoder.urls")),
]

from django.conf.urls.static import static
from django.conf import settings

url_patterns_for_media = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns = urlpatterns + url_patterns_for_media

Proyecto/AppCoder/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.



class Perfil(models.Model):
    descripcion = models.CharField(max_length=2200)    
    imagen = models.FileField(upload_to="media/avatares", null=True, blank=True)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.usuario}"


class Blog(models.Model):
    titulo = models.CharField(max_length=300)
    subtitulo = models.CharField(max_length=300)
    contenido = models.CharField(max_length=2200)
    fecha = models.DateTimeField(auto_now_add=True)    
    imagen = models.FileField(upload_to="media/posts", null=True, blank=True)
    autor = models.ForeignKey(User, on_delete=models.CASCADE)



    def __str__(self):
        
        return f"{self.titulo}"


class Comentario(models.Model):
     fecha = models.DateTimeField(auto_now_add=True)
     comentario = models.CharField(max_length=2200)
     autor = models.ForeignKey(User, on_delete=models.CASCADE)
     blog = models.ForeignKey(Blog, on_delete=models.CASCADE)

     def __str__(self):
        return f"@{self.autor}: '{self.blog}'"

class Avatar(models.Model):
    imagen = models.FileField(upload_to="media/avatares", null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.user} - {self.imagen}"
     

Proyecto/AppCoder/forms.py
from django import forms
from . import models
from django.contrib.auth.forms import UserCreationForm,UserModel


class PerfilFormulario(forms.ModelForm):
    class Meta:
        model = models.Perfil
        fields =["descripcion", "usuario"]
    
        widgets = {
            "descripcion":forms.TextInput(attrs={'class': 'form-control'}),                            
            "usuario" :forms.Select(attrs={'class':'form-control'}),
            "imagen" : forms.FileInput(attrs={'class':'form-control'})            
        }

class BlogFormulario(forms.ModelForm):
    class Meta:
        model = models.Blog
        fields =["titulo", "subtitulo", "contenido","autor","imagen"]
    
        widgets = {
            "titulo":forms.TextInput(attrs={'class': 'form-control'}),
            "subtitulo":forms.TextInput(attrs={'class': 'form-control'}),
            "contenido":forms.Textarea(attrs={'class': 'form-control'}),                   
            "autor" :forms.Select(attrs={'class':'form-control'}),
            "imagen" : forms.FileInput(attrs={'class':'form-control'})            
        }



class ComentarioFormulario(forms.ModelForm):
    class Meta:
        model = models.Comentario
        fields =["comentario","autor","blog"]
    
        widgets = {           
            "comentario":forms.Textarea(attrs={'class': 'form-control'})
        }


class UserCreationFormulario(UserCreationForm):    

    class Meta:
        model = UserModel
        fields = ["first_name", "last_name","email","username","password1", "password2"]
        #help_texts = {k: "" for k in fields}
        
        widgets = {
            "first_name":forms.TextInput(attrs={'class': 'form-control'}),
            "last_name":forms.TextInput(attrs={'class': 'form-control'}),
            "email":forms.TextInput(attrs={'class': 'form-control'}),           
            "password1":forms.PasswordInput(attrs={'class': 'form-control'}), 
            "password2":forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'por favor confirme su password'}),                   
                       
        }

class UserUpdateFormulario(UserCreationForm):    

    class Meta:
        model = UserModel
        fields = ["first_name", "last_name","email","password1", "password2"]
        #help_texts = {k: "" for k in fields}
        
        widgets = {
            "first_name":forms.TextInput(attrs={'class': 'form-control'}),
            "last_name":forms.TextInput(attrs={'class': 'form-control'}),
            "email":forms.TextInput(attrs={'class': 'form-control'}),           
            "password1":forms.PasswordInput(attrs={'class': 'form-control'}), 
            "password2":forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'por favor confirme su password'}),                   
                       
        }


        
       


class UserAvatarFormulario(forms.ModelForm):

    class Meta:
        model = models.Avatar
        fields = ["imagen"]

Proyecto/AppCoder/views.py
from django import forms, template
from django.shortcuts import redirect, render
from AppCoder.forms import BlogFormulario,ComentarioFormulario,UserCreationFormulario,UserUpdateFormulario
from . import models
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate,logout





def inicio_view(request):
    blogs = models.Blog.objects.all()    
    return render(request, "AppCoder/inicio.html",{"blogs":blogs})


def login_view1(request):
    return render(request, "AppCoder/login.html")


def login_view(request):
    if request.user.is_authenticated:
        return render(
            request,
            "AppCoder/inicio.html",
            {"mensaje": f"Ya estás autenticado: {request.user.username}"}
        )

    if request.method == "GET":
        return render(
            request,
            "AppCoder/login.html",
            {"form": AuthenticationForm()}
        )
    else:
        formulario = AuthenticationForm(request, data=request.POST)
        blogs = models.Blog.objects.all() 

        if formulario.is_valid():
            informacion = formulario.cleaned_data            
            usuario = informacion["username"]
            password = informacion["password"]

            modelo = authenticate(username=usuario, password=password)
            #print(modelo.id)
            login(request, modelo)
            perfil = models.Avatar.objects.filter(user=modelo)
            
            return render(
                request,
                "AppCoder/inicio.html",
                {"mensaje": f"Bienvenido {modelo.username}","perfil":perfil,"blogs":blogs}
            )
        else:
            return render(
                request,
                "AppCoder/login.html",
                {"form": formulario}
            )


def logout_view(request):
    logout(request)
    return render(request,"Appcoder/logout.html")

def about_view(request):   
    return render(request,"Appcoder/about.html")


def buscar_blog_view (request):
    
    if request.method == 'POST':
        datos = models.Blog.objects.filter(titulo__icontains = request.POST['titulo'])   
        msg = '' if len(datos) > 0 else 'No Existen registro Asociados a la busqueda'
        return render(request, 'AppCoder/buscarBlog.html',{'filtro':datos,'valida':msg}) 
    else:
        return render(request, 'AppCoder/buscarblog.html') 


def detalle_blog_view(request):
    return render(request, 'AppCoder/detalleblog.html')


def ver_blog_view(request,id_blog):
    
    if request.method == 'GET':
        datos = models.Blog.objects.filter(id = id_blog) 
        comentario = models.Comentario.objects.filter(blog_id = id_blog) 
        #msg = '' if len(datos) > 0 else 'No Existen registro Asociados a la busqueda'
        return render(request, 'AppCoder/verblog.html',{'filtro':datos,'comentario':comentario}) 
   
def nuevo_blog_view(request):
    return render(request, "AppCoder/inicio.html")   
    

def crear_blog_view(request):
    msg=''
    if request.method == 'POST':
        form = BlogFormulario(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            msg= "Blog ha sido creado en el Sistema."            
            return render(request, "AppCoder/nuevoblog.html", {'msg': msg,"form": BlogFormulario()})
    else:      
        miformulario = BlogFormulario()
        return render(request, "AppCoder/nuevoblog.html",{"form": miformulario,'msg': msg})


def crear_comentario_view(request):
    msg=''
    if request.method == 'POST':
        form = ComentarioFormulario(request.POST)
        
        if form.is_valid():
            form.save()
            datos = models.Blog.objects.filter(id = request.POST['blog']) 
            comentario = models.Comentario.objects.filter(blog_id = request.POST['blog']) 
            #msg = '' if len(datos) > 0 else 'No Existen registro Asociados a la busqueda'
            return render(request, 'AppCoder/verblog.html',{'filtro':datos,'comentario':comentario})                      
           
    else:      
        miformulario = ComentarioFormulario()
        return render(request, "AppCoder/comentario.html",{"form": miformulario,'msg': msg})


def cargar_blog_view(request,id_blog):
    datos = models.Blog.objects.get(pk = id_blog)
    form = BlogFormulario(request.POST or None,request.FILES or None,instance=datos)
    
    if form.is_valid():
        form.save()
        #msg= "Blog ha sido creado en el Sistema."            
        return render(request, "AppCoder/buscarblog.html")
        
         
    return render(request, 'AppCoder/updateblog.html',{'form':form})

def delete_blog_view(request,id_blog):
     datos = models.Blog.objects.get(pk = id_blog)
     datos.delete()
     return render(request, "AppCoder/buscarblog.html")
     


def crear_perfil_view(request):
    msg=''
    if request.method == 'POST':
        form = UserCreationFormulario(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            msg= "Blog ha sido creado en el Sistema."            
            return render(request, "AppCoder/nuevoperfil.html", {'msg': msg,"form": BlogFormulario()})
    else:      
        miformulario = UserCreationFormulario()
        return render(request, "AppCoder/nuevoperfil.html",{"form": miformulario,'msg': msg})



def cargar_perfil_view(request,id_user):
    blogs = models.Blog.objects.all() 
    datos_user = models.User.objects.get(pk = id_user)    
    form = UserUpdateFormulario(request.POST or None,request.FILES or None,instance=datos_user)
    #print(datos.user.username)
    
    if form.is_valid():        
        form.save()  
        return render(request, "AppCoder/inicio.html",{"blogs":blogs})
        
         
    return render(request, 'AppCoder/updateperfil.html',{'form':form})
    
  
    
    
    

 
    

Proyecto/AppCoder/templates/AppCoder/about.html
{% extends "AppCoder/inicio.html" %} 

{% load static %} 



{% block contenidoPrincipal %}

<section class="section transheader customtitle mx-auto  mb-4" style ="background: linear-gradient(45deg, #3ac5c8 1%, #0b509e 100%);">
    <div class="container">
        <div class="row">	
            <div class="col-md-12 col-md-offset-1 col-sm-12 text-center">
                <img class="img-fluid rounded mb-4" loading="lazy" src="{% static 'imagen/logo_software.png' %}" width="245" height="80" alt="BootstrapBrain Logo">
                <h4 class="text-white mb-3 lead">Soy Sergio Rivera, residente en Chile, apasionado por el desarrollo Software y la constante capacitación. Busco crecimiento continuo en el ámbito profesional, explorando nuevas oportunidades y adquiriendo habilidades para contribuir al mundo tecnológico.</h4>  
                <p class="text-white h5 lead">"Este proyecto es un blog centrado en lenguajes de programación, proporcionando a los usuarios un espacio para compartir conocimientos, experiencias y novedades en el mundo de la programación. Facilita la colaboración y discusión en torno a temas específicos de desarrollo de software."</p>
                <p class="lead"><a href="{% url 'home' %}" class="btn btn-warning btn-rounded">Volver a Inicio</a></p>
            </div><!-- end col -->
        </div><!-- end row -->
    </div><!-- end container -->
</section>
{% endblock %}

Proyecto/AppCoder/templates/AppCoder/buscarblog.html
{% extends "AppCoder/inicio.html" %} {% load static %} 
{% block contenidoPrincipal %}





  <section class="section transheader homepage parallax" data-stellar-background-ratio="0.5" style="padding-top:10px;padding-bottom:60px;min-height: 200px;background-image:url({% static 'imagen/bg_04.jpg' %});background-size: 100% 45%;">
    <div class="container">
      <div class="row">	
        <div class="col-md-12 col-md-offset-1 col-sm-12 text-center">
          <h2>Busqueda de Blogs</h2>         
          <form class="calculateform" method="POST" action="../Buscarblog/">
            {% csrf_token %} 
              <div class="item-box">
                  <div class="item-top form-inline">
                      <div class="form-group">
                        <div class="input-group2">
                          <span class="input-addon">
                            <i class="fa fa-search text-dark"></i>
                          </span>
                         <input type="text" class="form-control" id="titulo" name="titulo" placeholder="buscar por titulo" style="float: inline-start;"/> 
                        </div>
                         <input type="submit" name="send" value="Buscar"  class="btn btn-default" style="background: linear-gradient(45deg, #3ac5c8 1%, #0b509e 100%);" />                          
                      </div>
                     
                  </div>
              </div>
          </form>
        </div><!-- end col -->
      </div><!-- end row -->
    </div><!-- end container -->
  </section><!-- end section --> 

  <div class="row mx-auto ms-5">
  {% if filtro.count > 0 %}
  {% for blog in filtro  %}
  
    
    <div class="col-md-4">
      <div class="card p-2 mt-2 mb-2">
        {% if user.is_authenticated %} 
        <div class="position-absolute top-0 end-0 p-1">
          <a href="{% url 'updateblog' blog.id %}" class="btn btn-outline-info btn-sm" title="Editar"><i class="fa fa-edit"></i></a>
          <a href="{% url 'deleteblog' blog.id %}" class="btn btn-outline-danger btn-sm" title="Eliminar"><i class="fa fa-trash"></i></a>
        </div> 
        {% endif %}      
      <div class="ebook-details copybox row">        
        <div class="col-md-4">
          <img src="../../{{blog.imagen}}" width="100%" height="150px" alt="" class="img-responsive">
        </div>
        <div class="col-md-8">
          <div class="book-details">
            <ul class="list-inline" style="font-size: 12px;margin-bottom:0px">
              <li><span class="me-4 bd-gray-500"><i class="fa fa-calendar-o"></i> {{blog.fecha}}</span>         
             
            </ul>            
            <h3 class="bd-cyan-300">{{blog.titulo}}</h3>
            <small> {{blog.subtitulo}}</small>
            <p>{{blog.contenido}}</p>
            
            <a href="{% url 'verblog' blog.id %}" class="btn btn-transparent btn_blu"> Ver   <i class="fa fa-chevron-right"></i></a>
          </div><!-- end details -->
        </div><!-- end col -->
      </div><!-- end ebook-details -->
    </div>
    </div><!-- end col -->
    {% endfor %}
    {% endif %}
  </div>
   
  

  {% if filtro.count == 0 %}
    <div class="alert alert-info" role="alert">
        {{valida}} 
    </div>
    {% endif %}
  

{% endblock %}

Proyecto/AppCoder/templates/AppCoder/comentario.html
{% extends "AppCoder/inicio.html" %} {% load static %} 
{% block contenidoPrincipal %}

<div class="row">
  <div class="col-3 mx-auto mb-5">
    <div class="card">
      <div class="card-header bg-info">Nuevo Comentario</div>
      <div class="card-body">
        <form method="POST">
          {% csrf_token %} {{ form.as_p }}
          <button type="submit" class="btn btn-info">Guardar comentario</button>
        </form>
      </div>
    </div>
    
     
      {% if msg != '' %}
        <div class="alert bg-success mt-5 text-white" role="alert">
          {{msg}}
        </div>
      {% endif %}
  </div> 
</div>

{% endblock %}

Proyecto/AppCoder/templates/AppCoder/inicio.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Proyecto-Final</title>

    <link href="{% static 'bootstrap/css/bootstrap.min.css'  %}" rel="stylesheet" />
    <link href="{% static 'font-awesome/css/font-awesome.min.css'  %}" rel="stylesheet" />
    <link href="{% static 'css/style.css'  %}" rel="stylesheet" />
  </head>
  <body >
    {% include "AppCoder/layout/header.html" %}    

    {% block contenidoPrincipal %} 

    <section class="section-ini  homepage parallax"  style="background-image: url(&quot;{% static 'imagen/bg_04.jpg' %}&quot;)">
			<div class="container">
        <h1 class="mb-4 text-white">Bienvenidos a CodeBlogs</h1>
        <hr class="border-primary-subtle mb-4 text-white">
              <p class="lead mb-5"> Explora y accede a nuestros contenido.</p>
				<div class="row">	
					<div class="col-md-12 col-md-offset-1 col-sm-12 text-center">
						
						
            <div class="row">
              {% for blog in blogs  %}
              <div class="card-1 me-2 mb-2" style="width: 16rem;padding:4px">
                <img src="../../{{blog.imagen}}" width="100%" height="160px" alt="" class="">
                <div class="card-body">
                  <h5 class="card-title text-white lead">{{blog.titulo}}</h5>
                  
                  <a href="{% url 'verblog' blog.id %}" class="btn btn-primary-1">Ver</a>
                </div>
              </div>
              {% endfor  %} 
            </div>
					</div><!-- end col -->
				</div><!-- end row -->
			</div><!-- end container -->
		</section>
        
     
    {% endblock %}

    <script src="{% static 'bootstrap/js/bootstrap.min.js'  %}"></script>
  </body>
</html>

Proyecto/AppCoder/templates/AppCoder/login.html
{% extends "AppCoder/inicio.html" %} {% load static %} 
{% block contenidoPrincipal %}

<section class="py-md-5 py-xl-10  mb-5" style ="background: linear-gradient(45deg, #3ac5c8 1%, #0b509e 100%);">
    <div class="container">
      <div class="row gy-4 align-items-center">
        <div class="col-12 col-md-6 col-xl-7">
          <div class="d-flex justify-content-center text-bg-primary">
            <div class="col-12 col-xl-9">
              <img class="img-fluid rounded mb-4" loading="lazy" src="{% static 'imagen/blog.png' %}" width="245" height="80" alt="BootstrapBrain Logo">
              <hr class="border-primary-subtle mb-4">
              <h2 class="h5 lead mb-4 text-white">Este blog esta centrado en lenguajes de programación, proporcionando a los usuarios un espacio para compartir conocimientos, experiencias y novedades en el mundo de la programación.</h2>
              <p class="lead mb-5">Capacitacion Coderhouse @2023.</p>
              <div class="text-endx">
                <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" fill="currentColor" class="bi bi-grip-horizontal" viewBox="0 0 16 16">
                  <path d="M2 8a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm0-3a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm3 3a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm0-3a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm3 3a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm0-3a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm3 3a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm0-3a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm3 3a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm0-3a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                </svg>
              </div>
            </div>
          </div>
        </div>
        <div class="col-12 col-md-6 col-xl-5">
          <div class="card border-0 rounded-4" style="background: linear-gradient(45deg, #3ac5c8 1%, #0b509e 100%)">
            <div class="card-body p-3 p-md-4 p-xl-5">
              <div class="row" >
                <div class="col-12">
                  <div class="mb-4 text-white">
                    <h3>Iniciar Sesión</h3>
                    <p>No tienes una cuenta? <a href="{% url 'nuevoperfil' %}" class="text-warning">Registrate</a></p>
                  </div>
                </div>
              </div>
              <form action="{% url 'login' %}" method="POST">
                {% csrf_token %}               
                <div class="row gy-3 overflow-hidden">
                  <div class="col-12">
                    <div class="form-floating mb-3">
                    
                      <input type="text" class="form-control" name="username" id="id_username" placeholder="name@example.com" required>
                      <label for="usuario" class="form-label">Usuario</label>
                    </div>
                  </div>
                  <div class="col-12">
                    <div class="form-floating mb-3">
                      <input type="password" class="form-control" name="password" id="id_password" value="" placeholder="Password" required>
                      <label for="id_password" class="form-label">Password</label>
                    </div>
                  </div>
                  <div class="col-12">
                    <div class="form-check">
                     
                    </div>
                  </div>
                  <div class="col-12">
                    <div class="d-grid">
                      <button class="btn btn-warning btn-lg" type="submit">Inicia sesión ahora</button>
                    </div>
                  </div>
                </div>
              </form>  
          </div>
        </div>
      </div>
    </div>
  </section>



{% endblock %}

Proyecto/AppCoder/templates/AppCoder/login2.html
{% extends "AppCoder/inicio.html" %} 

{% load static %} 



{% block contenidoPrincipal %}
 
    <body style="background-color: #121212; color: #fff; font-family: Arial, sans-serif;">
        <div style="width: 400px; margin: 50px auto; background-color: #333; border: 1px solid #555; padding: 20px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.5); border-radius: 5px;">
            <form action="{% url 'login' %}" method="POST" style="display: flex; flex-direction: column;">
                {% csrf_token %}
    
                {{ form.as_p }}
    
                <input type="submit" value="Iniciar sesión" style="background-color: #1877f2; color: #fff; padding: 10px; border: none; border-radius: 3px; cursor: pointer;">
            </form>
        </div>
    </body>
    
    <style>
        input[type="text"],
        input[type="password"] {
            margin: 10px 0;
            padding: 10px;
            border: 1px solid #555;
            border-radius: 3px;
            background-color: #444;
            color: #fff;
        }

        input[type="submit"] {
            background-color: #1976D2;
            color: #fff;
            padding: 10px;
            border: none;
            border-radius: 3px;
            cursor: pointer;
        }

        input[type="submit"]:hover {
            background-color: #135e96;
        }
    </style>
{% endblock %}

Proyecto/AppCoder/templates/AppCoder/newblog.html
{% extends "AppCoder/inicio.html" %} {% load static %} 
{% block contenidoPrincipal %}

<div class="row">
  <div class="col-5 mx-auto mb-5">
    <div class="card">
      <div class="card-header bg-info">Nuevo Blog</div>
      <div class="card-body">
        <form method="POST">
          {% csrf_token %} {{ form.as_p }}
          <button type="submit" class="btn btn-info">Agregar Blog</button>
        </form>
      </div>
    </div>
    
     
      {% if msg != '' %}
        <div class="alert bg-success mt-5 text-white" role="alert">
          {{msg}}
        </div>
      {% endif %}
  </div> 
</div>

{% endblock %}

Proyecto/AppCoder/templates/AppCoder/verblog.html
{% extends "AppCoder/inicio.html" %} {% load static %} 
{% block contenidoPrincipal %}

<div class="row mt-5" style="margin: 0 20% 0 20%;">
<div class="content col-md-12 blog-alt">
    {% for blog in filtro  %}
  <div class="blog-box clearfix">
    <div class="media-box text-center feature-img">
      <img src="../../{{blog.imagen}}" alt="" width="100%" height="300px" class="img-responsive">
    </div><!-- end media-box -->
    <div class="blog-single">
      <div class="blog-meta">
       
        <ul class="list-inline">        
          <li><span class="me-4 fs-12 bd-cyan-300"><i class="fa fa-calendar-o"></i> {{blog.fecha}}</span>         
          <span class="bd-cyan-300"><i class="fa fa-comments-o "></i> {{comentario.count}} Comentarios</span>
        </ul>
      </div><!-- end meta -->
     
      <h3 class="post-title bd-indigo-400">{{blog.titulo}}</h3>
     
      <p>{{blog.contenido}}</p>
      {% endfor %}
     

     
    </div><!-- end blog-desc -->
  </div><!-- end blogbox -->

              <div class="blog-box clearfix">
                  <div class="custom-title">
                      <h4 class="bd-gray-400">{{comentario.count}} Comentarios </h4>
                      <hr class="text-primary">
                  </div><!-- end -->
                  {% for com in comentario  %}                  
                 
                  <div class="row">
                      <div class="col-md-12">
                          <div class="card2 p-3 mb-3">
                              <div class="card-body comments">
                                  <ul class="media-list" style="list-style:none">
                                      <li class="media">
                                          <div class="comment">                                              
                                                  <img src="{% static 'imagen/team_01.jpeg' %}" width="10%" height="10%" alt="" class="rounded-circle" style="float: inline-start;">
                                             
                                              <div class="media-body">
                                                <div>
                                                  <strong class="text-success">{{com.autor.first_name}} {{com.autor.last_name}}</strong>
                                                  <br>
                                                  <span class="text-muted">
                                                    <small class="text-muted">{{com.fecha}}</small></span>
                                                  </div>
                                                  
                                              </div>
                                              <div class="clearfix"></div>
                                              <p>{{com.comentario}} </p>
                                                 
                                          </div>
                                        </li>                                              
                                  </ul>
                              </div>
                          </div>
                      </div>
                  </div>
                  {% endfor %}
              </div><!-- end postpager -->

              <div class="blog-box clearfix text-primary">
                  <div class="custom-title">
                      <h4 class="bd-gray-400">Deja un Comentario</h4>
                  </div><!-- end about -->
                  
                  {% if user.is_authenticated %}
                  <div class="contact_form comment-form">
                      <form class="row" method="POST" action="../comentario/">
                        {% csrf_token %}
                        {% for bg in filtro  %}
                              <input type="hidden" class="form-control" id="id_autor" name="autor" value="{{user.id}}" >                         
                              <input type="hidden" class="form-control" id="id_blog" name="blog" value="{{bg.id}}">                        
                        {% endfor %}    
                          
                          <div class="col-md-12 col-sm-12">
                              <label class="bd-gray-400">Comentario <span class="required">*</span></label>
                              <textarea class="form-control" placeholder="" id="id_comentario" col="6" name="comentario" required  style="height: 149px;"></textarea>
                          </div>
                          <div class="col-md-12 col-sm-12 mt-2">
                              <input type="submit" value="Enviar comentario" class="btn btn-primary">
                          </div>
                      </form>
                  </div><!-- end commentform -->
                  {% else %}
                  <div class="alert alert-primary " role="alert">
                    Para agregar comentarios debes estar registrado, <p>No tienes una cuenta? <a href="{% url 'nuevoperfil' %}" class="text-primary">Registrate</a></p>
                  </div>
                  {% endif %}
              </div><!-- end postpager -->
</div>
</div> 
  

{% endblock %}